[package]
name = "feathrs"
version = "0.1.0"
edition = "2021"

<<<<<<< HEAD
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7"
ctrlc = "3.4.1"
termsize = "0.1.6"

=======
[dependencies]
libc = "0.2.155"
macon = "1.0.0"
terminal_size = "0.3.0"
termion = "4.0.2"
>>>>>>> v2
