[package]
name = "feathrs"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.8"
ctor = "0.2.8"
ctrlc = "3.4.4"
libc = "0.2.155"
macon = "1.0.0"
polonius-the-crab = "0.4.1"
term_size = "0.3.2"
termion = "4.0.2"
